[package]
name = "pdconfgen"
version = "0.0.1"
authors = ["Mathias Olsson <mathias.olsson@westcode.se>"]

[dependencies]
clap = "2.33"
der-parser = "1.1"
#nom="4.0"
#rusticata-macros = "1.0"
snmp-parser="0.3.0"